config/urls.py
from __future__ import annotations

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, ListView
from django.shortcuts import redirect
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    # path("", TemplateView.as_view(template_name="landing.html"), name="home"),
    path("", lambda request: redirect('/scanner/stock')),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("stratbot.users.urls", namespace="users")),
    path("account/", include("allauth.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    path("alerts/", include("stratbot.alerts.urls")),
    path("scanner/", include("stratbot.scanner.urls")),
    path("markets/", TemplateView.as_view(template_name="flowbite/markets.html"), name="markets"),
    path("docs/", TemplateView.as_view(template_name="flowbite/docs.html"), name="docs"),
    # path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # path("api/", include("stratbot.api.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

# TODO: use this instead of the above?
# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns  # type: ignore

stratbot/alerts/urls.py
from __future__ import annotations

from django.urls import path

from stratbot.alerts.views import UserSetupAlertListView

app_name = "alerts"
urlpatterns = [
    path(
        "setups/", view=UserSetupAlertListView.as_view(), name="user-setup-alert-list"
    ),
]

stratbot/api/urls.py
from django.urls import path, include
from .views import (
    SetupListApiView,
)

urlpatterns = [
    path('setups/<str:symbol>', SetupListApiView.as_view()),
]

stratbot/scanner/urls.py
from __future__ import annotations

from django.urls import path
from django.shortcuts import redirect
from django_filters.views import FilterView
from django.views.generic import TemplateView

from stratbot.scanner import views
from stratbot.scanner.filters import SetupFilter


app_name = "scanner"


urlpatterns = [
    # path("", SetupListView.as_view(template_name="dashboard/scanner.html"), name="scanner"),
    path("", lambda request: redirect('/scanner/stock'), name="default-redirect"),
    path("liveprice/", views.liveprice, name="liveprice"),
    path("flowbite/", views.flowbite, name="flowbite"),
    path("setups/", views.setups_view, name="setups-view"),
    path("grid/", views.grid, name="grid"),

    path('metrics/', views.advancing_declining, name='metrics'),
    path('sector-metrics/', views.sector_metrics, name='sector-metrics'),
    path('candle-metrics/', views.candle_metrics, name='sector-metrics'),
    # path("search/", FilterView.as_view(filterset_class=UserFilter, template_name="pages/search.html"), name="search"),
    # path("realtime/", TemplateView.as_view(template_name="flowbite/realtime.html"), name="realtime"),
    path("detail/<pk>/", views.SymbolDetailView.as_view(template_name="dashboard/symbol_detail.html"), name="symbol-detail"),
    path("symbols/", views.SymbolListView.as_view(template_name="dashboard/symbols_list.html"), name="symbols"),
    path("<symbol_type>/", views.SetupListView.as_view(template_name="flowbite/scanner.html"), name="scanner"),
    # path("<symbol_type>/", views.setup_list, name="scanner"),
]

stratbot/users/urls.py
from __future__ import annotations

from django.urls import path

from stratbot.users.views import user_detail_view, user_redirect_view, user_update_view


app_name = "users"

urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

stratbot/api/models.py
from django.db import models

# Create your models here.

stratbot/users/forms.py
from __future__ import annotations

from typing import Any

from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from stratbot.users.models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        fields = "__all__"
        field_classes: dict[str, Any] = {}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta:
        model = User
        fields = ("email", "name")
        field_classes: dict[str, Any] = {}
        error_messages = {"email": {"unique": _("This email has already been taken.")}}


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

stratbot/alerts/views.py
from __future__ import annotations

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView

from stratbot.alerts.models import UserSetupAlert


class UserSetupAlertListView(LoginRequiredMixin, ListView):
    model = UserSetupAlert
    ordering = ["-created", "-pk"]

    # NOTE: To see example pagination in action with Django's current default pagination
    # setup, see
    # https://docs.djangoproject.com/en/3.2/topics/pagination/#paginating-a-listview..
    #
    # ^ That being said, you might want to look into
    # https://github.com/photocrowd/django-cursor-pagination or something like that
    # if/once the number of records becomes high enough (like maybe >= 50,000 or >=
    # 100,000 or per-`User` or so). You also just may want to prune older alerts with
    # timeframes less than a day, etc. Up to you how you want to do, those are just some
    # examples.
    # ...
    # paginate_by = 100  # if pagination is desired
    # ...

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)[:50]

stratbot/api/views.py
from django.shortcuts import render
from django.utils import timezone

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions
from ..scanner.models import SymbolRec, Setup
from .serializers import SetupSerializer


class SetupListApiView(APIView):
    # add permission to check if user is authenticated
    # permission_classes = [permissions.IsAuthenticated]

    # 1. List all
    def get(self, request, *args, **kwargs):
        """
        List all setups for a given symbol
        """
        symbol = kwargs.get('symbol', None)
        if symbol is not None:
            if symbol == 'all':
                setups = Setup.objects.filter(expires__gt=timezone.now())
            else:
                setups = Setup.objects.filter(symbol_rec__symbol=symbol, expires__gt=timezone.now())
            serializer = SetupSerializer(setups, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response({"error": "No symbol provided"}, status=status.HTTP_400_BAD_REQUEST)

stratbot/events/views.py
from django.shortcuts import render

stratbot/scanner/api/views.py
from __future__ import annotations

from django.utils import timezone
from drf_spectacular.utils import extend_schema, OpenApiParameter, OpenApiTypes, OpenApiResponse, OpenApiExample
from rest_framework.exceptions import ValidationError, ParseError
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from rest_framework.views import APIView
import pandas_market_calendars as mcal

from stratbot.scanner.models.symbols import SymbolRec, Setup
from .serializers import SymbolRecSerializer, SetupSerializer, DateRangeSerializer


class SetupViewSet(RetrieveModelMixin, ListModelMixin, GenericViewSet):
    serializer_class = SetupSerializer
    queryset = Setup.objects.filter(expires__gt=timezone.now())

    @extend_schema(
        parameters=[
            OpenApiParameter(
                name='symbol',
                description='Symbol to filter setups, or "all" for all symbols',
                required=True,
                type=OpenApiTypes.STR,
                location=OpenApiParameter.QUERY
            ),
            OpenApiParameter(
                name='tf',
                description='Timeframe to filter setups: 15, 30, 60, 4H, 6H, 12H, D, W, M, Q',
                required=False,
                type=OpenApiTypes.STR,
                location=OpenApiParameter.QUERY
            )
        ]
    )
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        symbol = self.request.query_params.get('symbol')
        timeframe = self.request.query_params.get('tf')
        if not symbol:
            raise ValidationError({"error": "Invalid symbol parameter"})
        if symbol == 'all':
            return self.queryset if not timeframe else self.queryset.filter(tf=timeframe)
        filters = {'symbol_rec__symbol': symbol}
        if timeframe:
            filters['tf'] = timeframe
        return self.queryset.filter(**filters)


class SymbolRecViewSet(RetrieveModelMixin, ListModelMixin, GenericViewSet):
    serializer_class = SymbolRecSerializer
    queryset = SymbolRec.objects.all()

    @extend_schema(
        parameters=[
            OpenApiParameter(
                name='symbol',
                description='Stock or crypto symbol',
                required=False,
                type=OpenApiTypes.STR,
                location=OpenApiParameter.QUERY
            ),
            OpenApiParameter(
                name='symbol_type',
                description='Symbol type "stock", "crypto", or "all"',
                required=False,
                type=OpenApiTypes.STR,
                location=OpenApiParameter.QUERY
            ),
        ]
    )
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        # symbol_type = self.request.query_params.get('symbol_type', None)
        symbol_type = 'crypto'
        if symbol_type is not None:
            return self.queryset.filter(symbol_type=symbol_type, price__gt=0)
        else:
            return self.queryset


class MarketCalendarView(APIView):
    serializer_class = DateRangeSerializer

    @extend_schema(
        parameters=[
            OpenApiParameter(
                name='start_date',
                description='Start date in YYYY-MM-DD format',
                required=True,
                type=OpenApiTypes.STR,
                location=OpenApiParameter.QUERY
            ),
            OpenApiParameter(
                name='end_date',
                description='Start date in YYYY-MM-DD format',
                required=True,
                type=OpenApiTypes.STR,
                location=OpenApiParameter.QUERY
            ),
        ],
        responses={
            200: OpenApiResponse(
                description="Returns a list of market hours between start_date and end_date",
                response=OpenApiTypes.OBJECT,
                examples=[
                    OpenApiExample(
                        name="Market Calendar",
                        value=[
                            {
                                "index": "2023-06-01T00:00:00",
                                "market_open": "2023-06-01T13:30:00Z",
                                "market_close": "2023-06-01T20:00:00Z",
                            },
                            {
                                "index": "2023-06-02T00:00:00",
                                "market_open": "2023-06-02T13:30:00Z",
                                "market_close": "2023-06-02T20:00:00Z"}
                        ],
                        summary="Market Calendar Example",
                        description="Example market calendar with open and close times during regular trading hours."
                    ),
                ]
            )
        },
    )
    def get(self, request):
        serializer = self.serializer_class(data=request.query_params)
        serializer.is_valid(raise_exception=True)

        start_date = serializer.validated_data['start_date']
        end_date = serializer.validated_data['end_date']

        nyse = mcal.get_calendar('NYSE')
        schedule = nyse.schedule(start_date=start_date, end_date=end_date)

        schedule_json = schedule.reset_index().to_dict(orient='records')
        return Response(schedule_json)

stratbot/users/api/views.py
from __future__ import annotations

from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from stratbot.users.models import User

from .serializers import UserSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

stratbot/users/views.py
from __future__ import annotations

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseForbidden
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from stratbot.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "pk"
    slug_url_kwarg = "pk"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if self.request.user != obj: # and not self.request.user.is_superuser:
            return HttpResponseForbidden("You are not allowed to view this profile.")
        return obj


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

stratbot/templates/partials/footer.html
{% load static i18n %}
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © STAT Analytics, LLC
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

stratbot/templates/partials/head-css.html
{% load static i18n %}

<!-- App favicon -->
<link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}">

<!-- Theme Config Js -->
<script src="{% static 'assets/js/hyper-config.js' %}"></script>

<!-- App css -->
<link href="{% static 'assets/css/app-saas.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

<!-- Icons css -->
<link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />

<!-- Bootstrap JavaScript dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

stratbot/templates/partials/left-sidebar.html
{% load static i18n %}

<!-- ========== Left Sidebar Start ========== -->
<div class="leftside-menu">

    <!-- Brand Logo Light -->
    <a href="{% url 'dashboard:index' %}" class="logo logo-light">
        <span class="logo-lg">
            <img src="{% static 'assets/images/logo.png' %}" alt="logo">
        </span>
        <span class="logo-sm">
            <img src="{% static 'assets/images/logo-sm.png' %}" alt="small logo">
        </span>
    </a>

    <!-- Brand Logo Dark -->
    <a href="{% url 'dashboard:index' %}" class="logo logo-dark">
        <span class="logo-lg">
            <img src="{% static 'assets/images/logo-dark.png' %}" alt="dark logo">
        </span>
        <span class="logo-sm">
            <img src="{% static 'assets/images/logo-dark-sm.png' %}" alt="small logo">
        </span>
    </a>

    <!-- Sidebar Hover Menu Toggle Button -->
    <div class="button-sm-hover" data-bs-toggle="tooltip" data-bs-placement="right" title="Show Full Sidebar">
        <i class="ri-checkbox-blank-circle-line align-middle"></i>
    </div>

    <!-- Full Sidebar Menu Close Button -->
    <div class="button-close-fullsidebar">
        <i class="ri-close-fill align-middle"></i>
    </div>

    <!-- Sidebar -left -->
    <div class="h-100" id="leftside-menu-container" data-simplebar>
{#        <!-- Leftbar User -->#}
{#        <div class="leftbar-user">#}
{#            <a href="pages-profile.html">#}
{#                <img src="{% static 'assets/images/users/avatar-1.jpg' %}" alt="user-image" height="42" class="rounded-circle shadow-sm">#}
{#                <span class="leftbar-user-name mt-2">Dominic Keller</span>#}
{#            </a>#}
{#        </div>#}

        <!--- Sidemenu -->
        <ul class="side-nav">
            <li class="side-nav-title">SCREENER</li>

            <li class="side-nav-item">
                <a href="{% url 'scanner:scanner' 'stock' %}" class="side-nav-link">
                    <i class="uil-chart-line"></i>
                    <span> Stocks </span>
                </a>
            </li>
            <li class="side-nav-item">
                <a href="{% url 'scanner:scanner' 'crypto' %}" class="side-nav-link">
                    <i class="uil-bitcoin-circle"></i>
                    <span> Crypto </span>
                </a>
            </li>
            <li class="side-nav-item">
                <a href="{% url 'scanner:symbols' %}" class="side-nav-link">
                    <i class="uil-question-circle"></i>
                    <span> Symbols Scanned </span>
                </a>
            </li>

            <li class="side-nav-title side-nav-item mt-2">OTHER</li>

            <li class="side-nav-item">
                <a href="{% url 'markets' %}" class="side-nav-link">
                    <i class="uil-graph-bar"></i>
                    <span> Market Overview </span>
                </a>
            </li>

        </ul> <!--- End Sidemenu -->

        <!-- Help Box -->
        <div class="help-box text-white text-center">
            <a href="javascript: void(0);" class="float-end close-btn text-white">
                <i class="mdi mdi-close"></i>
            </a>
            <img src="{% static 'assets/images/svg/help-icon.svg' %}" height="90" alt="Helper Icon Image" />
            <h5 class="mt-3">STAT Trading</h5>
            <p class="mb-3">Join our community and learn #thestrat.</p>
            <a href="https://stratalerts.com" target="_blank" class="btn btn-secondary btn-sm">Upgrade</a>
        </div> <!-- end Help Box -->

        <!-- Discord Button -->
        <div class="help-box text-white text-center mt-3">
            <a href="https://stratalerts.com/discord" class="btn btn-primary" role="button">
              <i class="mdi mdi-discord"></i> {% trans "Free Discord" %} </a>
        </div> <!-- end Discord Button -->

        <div class="clearfix"></div>
    </div>
</div>
<!-- ========== Left Sidebar End ========== -->