config/urls.py
from __future__ import annotations

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, ListView
from django.shortcuts import redirect
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    # path("", TemplateView.as_view(template_name="landing.html"), name="home"),
    path("", lambda request: redirect('/scanner/stock')),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("stratbot.users.urls", namespace="users")),
    path("account/", include("allauth.urls")),
    path("prometheus/", include("django_prometheus.urls")),
    path("alerts/", include("stratbot.alerts.urls")),
    path("scanner/", include("stratbot.scanner.urls")),
    path("markets/", TemplateView.as_view(template_name="flowbite/markets.html"), name="markets"),
    path("docs/", TemplateView.as_view(template_name="flowbite/docs.html"), name="docs"),
    # path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # path("api/", include("stratbot.api.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

# TODO: use this instead of the above?
# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns  # type: ignore

stratbot/alerts/urls.py
from __future__ import annotations

from django.urls import path

from stratbot.alerts.views import UserSetupAlertListView

app_name = "alerts"
urlpatterns = [
    path(
        "setups/", view=UserSetupAlertListView.as_view(), name="user-setup-alert-list"
    ),
]

stratbot/api/urls.py
from django.urls import path, include
from .views import (
    SetupListApiView,
)

urlpatterns = [
    path('setups/<str:symbol>', SetupListApiView.as_view()),
]

stratbot/scanner/urls.py
from __future__ import annotations

from django.urls import path
from django.shortcuts import redirect
from django_filters.views import FilterView
from django.views.generic import TemplateView

from stratbot.scanner import views
from stratbot.scanner.filters import SetupFilter


app_name = "scanner"


urlpatterns = [
    # path("", SetupListView.as_view(template_name="dashboard/scanner.html"), name="scanner"),
    path("", lambda request: redirect('/scanner/stock'), name="default-redirect"),
    path("liveprice/", views.liveprice, name="liveprice"),
    path("flowbite/", views.flowbite, name="flowbite"),
    path("setups/", views.setups_view, name="setups-view"),
    path("grid/", views.grid, name="grid"),

    path('metrics/', views.advancing_declining, name='metrics'),
    path('sector-metrics/', views.sector_metrics, name='sector-metrics'),
    path('candle-metrics/', views.candle_metrics, name='sector-metrics'),
    # path("search/", FilterView.as_view(filterset_class=UserFilter, template_name="pages/search.html"), name="search"),
    # path("realtime/", TemplateView.as_view(template_name="flowbite/realtime.html"), name="realtime"),
    path("detail/<pk>/", views.SymbolDetailView.as_view(template_name="dashboard/symbol_detail.html"), name="symbol-detail"),
    path("symbols/", views.SymbolListView.as_view(template_name="dashboard/symbols_list.html"), name="symbols"),
    path("<symbol_type>/", views.SetupListView.as_view(template_name="flowbite/scanner.html"), name="scanner"),
    # path("<symbol_type>/", views.setup_list, name="scanner"),
]

stratbot/users/urls.py
from __future__ import annotations

from django.urls import path

from stratbot.users.views import user_detail_view, user_redirect_view, user_update_view


app_name = "users"

urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

stratbot/api/models.py
from django.db import models

# Create your models here.

stratbot/scanner/forms.py
from __future__ import annotations

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Div, Fieldset, Layout, HTML, Reset, Row
from crispy_tailwind.layout import Reset, Submit, Button
from django import forms

from stratbot.scanner.models.symbols import Direction, SymbolType
from stratbot.scanner.models.timeframes import Timeframe


class SetupFilterForm(forms.Form):

    symbol_type = forms.ChoiceField(
        initial="stock",
        required=True,
        # choices=[
        #     ("", "-----"),
        # ]
        choices=SymbolType.choices,
    )

    tf = forms.ChoiceField(
        label="Timeframe",
        initial="D",
        # choices=[
        #     ("all", "-----"),
        # ]
        choices=Timeframe.choices[2:],
        required=False,
        # widget=forms.HiddenInput(),
    )

    pattern = forms.ChoiceField(
        label="Pattern",
        choices=(
            ("", "-----"),
            ("x-1", "x-1-x"),
            ("1-1", "1-1-x"),
            ("1-2", "1-2-x"),
            # ("1-3", "1-3-×"),
            ("2-1", "2-1-x"),
            ("2-2", "2-2-x"),
            # ("2-3", "2-3-×"),
            ("3-1", "3-1-x"),
            ("3-2", "3-2-x"),
            ("x-3", "x-3-x"),
            ("1-3", "1-3-x"),
        ),
        required=False,
        initial="",
    )

    current_candle = forms.ChoiceField(
        label="CC",
        choices=(
            ("", "-----"),
            ("1", "1"),
            ("2U", "2U"),
            ("2D", "2D"),
            ("3", "3"),
        ),
        required=False,
        initial="",
    )

    tfc = forms.ChoiceField(
        label="FTFC",
        choices=(
            ("", "-----"),
            ("BULL", "BULL"),
            ("BEAR", "BEAR"),
        ),
        required=False,
        initial="",
    )

    candle_tag = forms.ChoiceField(
        label="Tags",
        choices=(
            ("", "-----"),
            ("2d green hammer", "2d green hammer"),
            ("2u red shooter", "2u red shooter"),
            ("hammer", "hammer"),
            ("shooter", "shooter"),
            ("hammer OR shooter", "hammer OR shooter"),
            ("hammer shooter", "hammer + shooter"),
            ("shooter hammer", "shooter + hammer"),
            ("2d green", "2d green"),
            ("2u red", "2u red"),
        ),
        required=False,
        initial="",
    )

    direction = forms.ChoiceField(
        label="Direction",
        choices=[
            (0, "-----")
        ] + Direction.choices,
        required=False,
        initial="",
    )

    in_force = forms.ChoiceField(
        label="In Force",
        choices=[
            ("", "-----"),
            (True, "Yes"),
            (False, "No"),
        ],
        required=False,
        initial="",
    )

    hit_magnitude = forms.ChoiceField(
        label="Hit Mag",
        choices=[
            ("", "-----"),
            (True, "Yes"),
            (False, "No"),
        ],
        required=False,
        initial=False,
    )

    potential_outside = forms.ChoiceField(
        label="P3",
        choices=(
            ("", "-----"),
            (True, "Yes"),
            (False, "No"),
        ),
        required=False,
        initial="",
    )

    rr__gte = forms.DecimalField(
        label="RR Min",
        widget=forms.NumberInput(
            attrs={
                'class': 'numberinput form-input',
                'style': 'width: 5em;'
            }
        ),
        required=False,
        initial=0,
    )

    pmg__gte = forms.IntegerField(
        label="PMG",
        initial=0,
        required=False,
        widget=forms.NumberInput(
            attrs={
                'class': 'numberinput form-input',
                'style': 'width: 5em;',
            },
        ),
    )

    gapped = forms.ChoiceField(
        label="Gappers",
        choices=(
            ("", "-----"),
            (True, "Yes"),
            (False, "No"),
        ),
        required=False,
        initial="",
    )

    negated = forms.ChoiceField(
        label="Negated",
        choices=(
            ("", "-----"),
            (True, "Yes"),
            (False, "No"),
        ),
        required=False,
        initial=False,
    )

    symbol_rec__atr__gte = forms.FloatField(
        label="ATR $",
        required=False,
        widget=forms.NumberInput(
            attrs={
                'class': 'numberinput form-input',
                'style': 'width: 5em;',
            },
        ),
        initial=0,
    )

    symbol_rec__atr_percentage__gte = forms.FloatField(
        label="ATR %",
        required=False,
        widget=forms.NumberInput(
            attrs={
                'class': 'numberinput form-input',
                'style': 'width: 5em;',
            },
        ),
        initial=0,
    )

    min_price = forms.IntegerField(
        label="Min Price",
        widget=forms.NumberInput(attrs={
            'class': 'numberinput form-input',
            'style': 'width: 5em;',
        }),
        required=False,
        initial=0,
    )

    max_price = forms.IntegerField(
        label="Max Price",
        widget=forms.NumberInput(attrs={
            'class': 'numberinput form-input',
            'style': 'width: 5em;',
        }),
        required=False,
    )

    sector = forms.ChoiceField(
        label="Sector",
        choices=(
            ("", "-----"),
            ('communication-services', 'Communications'),
            ('consumer-cyclical', 'Consumer Cyclical'),
            ('consumer-defensive', 'Consumer Defensive'),
            ('energy', 'Energy'),
            ('financial-services', 'Financial'),
            ('real-estate', 'Real Estate'),
            ('healthcare', 'Healthcare'),
            ('technology', 'Tech'),
            ('basic-materials', 'Materials'),
            ('industrials', 'Industrials'),
            ('utilities', 'Utilities'),
        ),
        required=False,
        initial="",
    )

    industry = forms.CharField(
        label="Industry",
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'numberinput form-input',
                'style': 'width: 8em;',
            },
        ),
    )

    market_cap = forms.ChoiceField(
        label="Market Cap",
        choices=(
            (0, "-----"),
            (1000000000, '1B+'),
            (5000000000, '5B+'),
            (10000000000, '10B+'),
            (50000000000, '50B+'),
            (100000000000, '100B+'),
            (500000000000, '500B+'),
            (1000000000000, '1T+'),
        ),
        required=False,
        initial="50000000000",
    )

    def __init__(self, *args, request=None, is_stock=False, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_method = "GET"
        self.helper.form_id = "setup-filter-form-id"

        primary_row_layout = [
            Column("tf"),
            Column("pattern", css_class="px-1"),
            Column("candle_tag", css_class="px-1"),
            Column("direction", css_class="px-1"),
            Column("in_force", css_class="px-1"),
            Column("hit_magnitude", css_class="px-1"),
            Column("current_candle", css_class="px-1"),
            Column("tfc", css_class="px-1"),
            Column("pmg__gte", css_class="px-1"),
            Column(
                "potential_outside",
                data_toggle="tooltip",
                data_placement="top",
                title="SSS50% Rule Triggered",
                css_class="flex flex-wrap -mx-1"
            ),
        ]

        secondary_row_layout = [
            Column("symbol_rec__atr__gte", css_class="px-1"),
            Column("symbol_rec__atr_percentage__gte", css_class="px-1"),
            Column("min_price", css_class="px-1"),
            Column("max_price", css_class="px-1"),
            Column(
                "rr__gte",
                css_class="px-1",
                data_toggle="tooltip",
                data_placement="top",
                title="Risk/Return expresssed in Rs"
            ),
        ]

        if is_stock:
            choices = []
            for timeframe in Timeframe.choices:
                if timeframe[0] not in ('1', '5', '6H', '12H'):
                    choices.append(timeframe)
            # self.fields['tf'].choices = [
            #     ("all", "-----"),
            # ] + choices[2:]
            self.fields['tf'].choices = choices

            self.fields['market_cap'] = forms.ChoiceField(
                label="Market Cap",
                choices=(
                    (0, "-----"),
                    (1000000000, '1B+'),
                    (5000000000, '5B+'),
                    (10000000000, '10B+'),
                    (50000000000, '50B+'),
                    (100000000000, '100B+'),
                    (500000000000, '500B+'),
                    (1000000000000, '1T+'),
                ),
                required=False,
                initial="50000000000",
            )
            secondary_row_layout.append(Column("market_cap", css_class="px-1"))

            self.fields['spread'] = forms.ChoiceField(
                label="Spread",
                choices=(
                    ("", "-----"),
                    (0.10, "< 0.10%"),
                    (0.25, "< 0.25%"),
                    (0.5, "< 0.5%"),
                    (1, "< 1.0%"),
                    (2, "< 2.0%"),
                    (3, "< 3.0%"),
                    (4, "< 4.0%"),
                    (5, "< 5.0%"),
                ),
                required=False,
                initial="",
            )
            secondary_row_layout.append(Column("spread", css_class="px-1"))

            self.fields['sector'] = forms.ChoiceField(
                label="Sector",
                choices=(
                    ("", "-----"),
                    ('communication-services', 'Communications'),

stratbot/alerts/views.py
from __future__ import annotations

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView

from stratbot.alerts.models import UserSetupAlert


class UserSetupAlertListView(LoginRequiredMixin, ListView):
    model = UserSetupAlert
    ordering = ["-created", "-pk"]

    # NOTE: To see example pagination in action with Django's current default pagination
    # setup, see
    # https://docs.djangoproject.com/en/3.2/topics/pagination/#paginating-a-listview..
    #
    # ^ That being said, you might want to look into
    # https://github.com/photocrowd/django-cursor-pagination or something like that
    # if/once the number of records becomes high enough (like maybe >= 50,000 or >=
    # 100,000 or per-`User` or so). You also just may want to prune older alerts with
    # timeframes less than a day, etc. Up to you how you want to do, those are just some
    # examples.
    # ...
    # paginate_by = 100  # if pagination is desired
    # ...

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)[:50]

stratbot/api/views.py
from django.shortcuts import render
from django.utils import timezone

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions
from ..scanner.models import SymbolRec, Setup
from .serializers import SetupSerializer


class SetupListApiView(APIView):
    # add permission to check if user is authenticated
    # permission_classes = [permissions.IsAuthenticated]

    # 1. List all
    def get(self, request, *args, **kwargs):
        """
        List all setups for a given symbol
        """
        symbol = kwargs.get('symbol', None)
        if symbol is not None:
            if symbol == 'all':
                setups = Setup.objects.filter(expires__gt=timezone.now())
            else:
                setups = Setup.objects.filter(symbol_rec__symbol=symbol, expires__gt=timezone.now())
            serializer = SetupSerializer(setups, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response({"error": "No symbol provided"}, status=status.HTTP_400_BAD_REQUEST)

stratbot/events/views.py
from django.shortcuts import render

stratbot/templates/dashboard/scanner.html
{% extends "vertical_base.html" %}
{% load static i18n crispy_forms_tags dashtags humanize %}

{% block title %}{% trans "Screener" %}: {{ symbol_type|title }}{% endblock title %}

{% block content %}
  <!-- Start Content-->
  <div class="container-fluid">

    <!-- Beta Warning -->
    <div class="row">
      <div class="alert alert-warning alert-dismissible fade show text-center mt-2" role="alert">
        BETA VERSION - USE WITH CAUTION
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div> <!-- End Beta Warning -->

    <!-- Important Notes -->
    <div class="row">
      <div class="card">
        <div class="card-body">
          <h4 class="header-title mb-2">IMPORTANT NOTES</h4>
          <ul>
            <li class="mb-2">
              We do not currently have full market coverage (it's incredibly expensive), so OHLC values on intraday
              timeframes may be off by a few cents compared to TradingView, thinkorswim, and other brokers.
            </li>
            <li>
              Setups on the 15, 30, 60, 4H, and D timeframes are re-processed at 12:15am EST each day and include full
              market coverage so OHLC values should match your platform.
            </li>
          </ul>

          <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#scrollable-modal">
            How This Works
          </button>
          <div class="modal fade" id="scrollable-modal" tabindex="-1" role="dialog"
               aria-labelledby="scrollableModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="scrollableModalTitle">Scanner Details - Updated: 2023-06-30</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
                </div>
                <div class="modal-body">
                  This section will be updated over time. For now, here are some details about the scanner.
                  <hr style="border-top: 1px solid;">

                  Crypto data from Bybit with additional exchanges coming in the future.
                  <br><br>

                  RR: estimate using a stop-loss at 50% of the trigger candle<br>
                  PMG: identified by 5 or more consecutive HH/LL
                  <br><br>

                  When TFC is displayed in white, last price == open (no direction).
                  <br><br>

                  IMPORTANT: This website is a tool. As always, use your own judgement and rules when entering and
                  exiting trades.
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
          </div><!-- /.modal -->
        </div>
      </div>
    </div> <!-- End Important Notes -->

    <!-- start page title -->
    <div class="row">
      <div class="col-12">
        <div class="page-title-box">
          <div class="page-title-right">
            <ol class="breadcrumb m-0">
              <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
              <li class="breadcrumb-item active">{{ symbol_type|title }}</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!-- end page title -->

    <div class="col-12">
      {% crispy setup_filter_form %}
    </div>

    <div class="container-fluid p-0 my-3">
      <nav class="navbar navbar-light bg-light" style="padding-left: 5px;">
        <form class="form-inline" id="tf-list">
          <a class="btn btn-xs {% if selected_tf == 'all' %}btn-secondary{% else %}btn-outline-secondary{% endif %}"
             role="button" data-tf="all" href="{% url 'scanner:scanner' symbol_type=symbol_type %}?tf=">ALL</a>
          {% for timeframe in timeframes %}
            <a
              class="btn btn-xs {% if selected_tf == timeframe %}btn-secondary{% else %}btn-outline-secondary{% endif %}"
              role="button"
              data-tf="{{ timeframe }}" href="{% url 'scanner:scanner' symbol_type=symbol_type %}?tf={{ timeframe }}">{{ timeframe }}</a>
          {% endfor %}
        </form>
      </nav>
    </div>

{#    <div class="row">#}
{#        <div class="progress">#}
{#          <div class="progress-bar" role="progressbar" style="width: 15%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>#}
{#          <div class="progress-bar bg-success" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>#}
{#          <div class="progress-bar bg-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>#}
{#        </div>#}
{#    </div>#}

    <div class="table-responsive scrollbar">
      {% regroup object_list by tf as by_timeframe %}
      {% for tf in by_timeframe %}
        <table class="table table-hover">
          <thead class="sticky-top">
          <tr>
            <th scope="col">SYMBOL</th>
            <th scope="col">TFC</th>
            <th scope="col">TF</th>
            <th scope="col">STRAT</th>
            <th scope="col">DIRECTION</th>
            <th scope="col">PRICE</th>
            <th scope="col">TRIGGER</th>
            {#          <th scope="col">IN FORCE</th>#}
            <th scope="col">T1</th>
            <th scope="col" data-bs-toggle="tooltip" data-bs-placement="top"
                title="Risk/Return using a stop at the 50% level of the previous candle">RR</th>
            {#          <th scope="col">PMG</th>#}
            <th scope="col">TAGS</th>
            <th scope="col">VOLUME</th>
{#            <th scope="col">RVOL</th>#}
            <th scope="col">ATR 14D</th>
            <th scope="col">EXPIRES</th>
            {#          <th scope="col">SSS50</th>#}
            {#          <th scope="col">NEGATED</th>#}
          </tr>
          </thead>
          <tbody>
          {% for setup in tf.list %}
            <tr class="hover-actions-trigger m-1 p-1 {% bg_color_based_on_direction setup %}">
            <td class="align-middle text-nowrap m-1 p-1">
{#            <td class="align-middle text-nowrap m-1 p-1" data-bs-toggle="popover" #}
{#                title="Popover title" #}
{#                data-bs-content="Popover content goes here.">#}
{#              <a href="{% url 'scanner:symbol-detail' setup.symbol_rec.pk %}">#}
                <strong>{{ setup.symbol_rec.symbol }}</strong>
{#              </a>#}
            </td>
            <td class="align-middle text-nowrap m-1 p-1">
              <strong>{% tfc_to_html setup.symbol_rec.price setup.symbol_rec.tfc %}</strong>
            </td>
            <td class="align-middle text-nowrap m-1 p-1"><strong>{{ setup.tf }}</strong></td>
            <td class="align-middle text-nowrap m-1 p-1">
              <strong>{{ setup.pattern.0 }}-{{ setup.pattern.1 }}</strong>
            </td>
            <td class="align-middle text-nowrap m-1 p-1">
              {% if setup.direction == 1 %}BULL{% else %}BEAR{% endif %}
            </td>
            <td class="align-middle text-nowrap m-1 p-1">{{ setup.symbol_rec.price }}</td>
            <td class="align-middle text-nowrap m-1 p-1">{{ setup.trigger }}</td>
            {#            <td class="align-middle text-nowrap">{{ setup.in_force }}</td>#}
            <td class="align-middle text-nowrap m-1 p-1">{{ setup.targets.0 }}</td>
            <td class="align-middle text-nowrap m-1 p-1">{{ setup.rr }}</td>
            {#            <td class="align-middle text-nowrap"><strong>{{ setup.pmg }}</strong></td>#}

            <td class="align-middle text-nowrap m-1 p-1">{{ setup.candle_tag }}</td>
            <td class="align-middle text-nowrap m-1 p-1">
              {{ setup.symbol_rec.todays_volume|divide:1_000_000|floatformat:"2" }} M
            </td>
{#            <td class="align-middle text-nowrap m-1 p-1">{% rvol setup %}</td>#}
            <td class="align-middle text-nowrap m-1 p-1">
              {%  if setup.trigger < 0.001 %}
                ${{ setup.symbol_rec.calculate_atr|floatformat:"6" }}
              {%  else %}
                ${{ setup.symbol_rec.calculate_atr|floatformat:"2" }}
              {%  endif %}
            </td>
            <td class="align-middle text-nowrap m-1 p-1">{{ setup.expires|date:"Y-m-d H:i e" }}</td>
            {#            <td class="align-middle text-nowrap">{{ setup.potential_outside }}</td>#}
            {#            <td class="align-middle text-nowrap">{{ setup.negated }}</td>#}
          {% endfor %}
          </tr>
          </tbody>
        </table><br>
      {% endfor %}
    </div>

  </div> <!-- container -->
{% endblock %}


{% block extra_javascript %}
{#  <script>#}
{#    $(function () {#}
{#      $('[data-toggle="tooltip"]').tooltip()#}
{#    })#}
{#  </script>#}

  <script>
      $(document).ready(function(){
      $('[data-bs-toggle="popover"]').popover();
  });
  </script>

  <script>
    document.querySelectorAll("#tf-list a").forEach((linkElement) => {
      let onTfLinkClick = (event) => {
        event.preventDefault();
        let element = event.target;
        let tf = element.dataset.tf;
        let dropdownElement = document.querySelector("#id_tf");
        dropdownElement.selected = true
        dropdownElement.value = tf;
        let submitButton = document.querySelector("#setup-filter-form-id #submit-id-submit");
        submitButton.click();
      }
      linkElement.addEventListener("click", onTfLinkClick);
    });
  </script>

  <!-- Apex js -->
  {#<script src="{% static 'js/vendor/apexcharts.min.js' %}"></script>#}

  <!-- demo:js -->
  {#<script src="https://apexcharts.com/samples/assets/stock-prices.js"></script>#}
  {#<script src="https://apexcharts.com/samples/assets/series1000.js"></script>#}
  {#<script src="https://apexcharts.com/samples/assets/github-data.js"></script>#}
  {#<script src="https://apexcharts.com/samples/assets/irregular-data-series.js"></script>#}
{#  <script src="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.js"></script>#}
{#  <script#}
{#    src="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/sticky-header/bootstrap-table-sticky-header.min.js"></script>#}
{% endblock %}


{% block extra_css %}
{#  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.css">#}
{#  <link rel="stylesheet"#}
{#        href="https://unpkg.com/bootstrap-table@1.21.0/dist/extensions/sticky-header/bootstrap-table-sticky-header.css">#}
{% endblock extra_css %}